---
- name: "add nodejs 13"
  become: true
  shell: |
     curl -fsSL https://deb.nodesource.com/setup_13.x | bash -
     apt-get install -y nodejs
     
- name: "install pm2 globally"
  become: true
  npm:
    name: pm2
    global: yes